### ISSUE TITLE
Long app names are not wrapped

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launchpad#14]
If the app name does not contain spaces, it will overflow from the text container. Change CSS rules so that it wraps even if there are no spaces.

![2017-07-13 10_55_54-](https://user-images.githubusercontent.com/566463/28158434-fa7896dc-67b9-11e7-9f70-b60c9a42ee0c.png)

**Comment by Mihaiii** [comment]
:)))))

<img width="58" alt="ce" src="https://user-images.githubusercontent.com/8951553/28832548-0e59c9fa-76dd-11e7-8f06-89f794bdc02f.png">

**Comment by Mihaiii** [comment]
Closing as done.
