### ISSUE TITLE
Remove the dependency on juicy-tile-table

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launchpad#15]
Launchpad app should use CSS Grid Layout, not `juicy-tile-table`.

Part of https://github.com/Starcounter/RebelsLounge/issues/72

**Comment by warpech** [comment]
After this is done, check if `juicy-tile-table` is used in other (not frozen) apps. 

If not, then remove the topic `used-in-starcounter-apps` from https://github.com/juicy/juicy-tile-table

If yes, remove usage of `juicy-tile-table` from these apps.

**Comment by Mihaiii** [comment]
Closing as done.
`juicy-tile-table` is not used in any other app.
