### ISSUE TITLE
Common settings page

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launchpad#18]
Launchpad should implement the proposal from https://github.com/Starcounter/Guidelines/issues/33

@bouguila could you please implement this? 

You can take the cog icon from our old [Launcher](https://github.com/StarcounterAppsFreezer/Launcher/blob/master/src/Launcher/wwwroot/Launcher/images/cog.svg) app, just remember that it should pasted inline in HTML.

Suggested reviewer: @Mihaiii

**Comment by bouguila** [comment]
@warpech does the "Launchpad" itself return a setting view page, or should it return its MasterPage, or it has to return nothing?

**Comment by warpech** [comment]
I was thinking that Launchpad should return its own page `/launchpad/settings`. That page has a nice heading ("Settings") and a nested empty page that is mapped to the token `settings`.

**Comment by bouguila** [comment]
@warpech ok that's what i also thought! 
and concerning the icon being pasted as inline in html, could you please take a look at the changes and tell me if is that the correct way?

**Comment by warpech** [comment]
> concerning the icon being pasted as inline in html, could you please take a look at the changes and tell me if is that the correct way?

I've responded in https://github.com/StarcounterApps/Launchpad/pull/19#issuecomment-320892062

**Comment by bouguila** [comment]
closing as done in 6fdb214
