### ISSUE TITLE
Use uniform batch scripts

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Launchpad#2]
Use uniform batch scripts as presented in https://starcounter.gitbooks.io/guidelines/content/batch-files.html

Discussion: https://github.com/Starcounter/Guidelines/issues/6

**Comment by warpech** [comment]
Some projects output the exe files to `./bin/Debug` instead of `./src/<appname>/bin/Debug`.

The latter form is expected (see https://starcounter.gitbooks.io/guidelines/content/project_structure.html)

If this solution does not output the exe files to the desired paths (both in msbuild and in VS), please fix that immediately too.

**Comment by warpech** [comment]
Taking this on me

**Comment by warpech** [comment]
Done

**Comment by Mackiovello** [comment]
Isn't package.bat https://github.com/StarcounterApps/Launchpad/commit/7eacaee2a429e71f55018ef7e051bfd4ba2b30bd#diff-83905f0949601bcd26f8df609e66b6c6 the old one?

**Comment by warpech** [comment]
Definitely yes, thank you for noticing. Fixed.

**Comment by KmaTTi89** [comment]
Done in https://github.com/StarcounterApps/Launchpad/pull/4
