### ISSUE TITLE
AppName html property should be case insensitive in launchpad-panel element

### ISSUE THREAD

**Issue by habib535** [StarcounterApps/Launchpad#20]
In all our json files the name of html property is declared as `"Html"` (first letter is caps on) but for launchpad-icon we don't follow this convention and in every app `AppName.json` looks like this.
```
{
  "name": "Search",
  "description": "Search",
  "html": "/Search/viewmodels/AppIcon.html"
}
```

Because I was using the general practice so the Icon for search app was not showing up. We need to update the [element](https://github.com/StarcounterApps/Launchpad/blob/master/src/Launchpad/wwwroot/Launchpad/elements/launchpad-panel/launchpad-panel.html#L63) so it always convert the html property to lower case.

**Comment by Mihaiii** [comment]
Closing as done.
