### ISSUE TITLE
Multiple icons from one app

### ISSUE THREAD

**Issue by mmnosek** [StarcounterApps/Launchpad#3]
This is a demand from SWO project. We need to expose couple icons with different links and descriptions from one app.

https://github.com/Starcounter/Starcounter/issues/4061 required

cc @warpech

**Comment by warpech** [comment]
To be investigated soon by @un-tone after https://github.com/StarcounterApps/Launchpad/pull/1 is finished.

**Comment by warpech** [comment]
By all means this should be doable now. @Mihaiii could you pls check if this can be done?

**Comment by Mihaiii** [comment]
Yes, now it is doable.
I made 2 demo branches for this:
- https://github.com/StarcounterApps/Content/tree/demo/multiple-app-icons
- https://github.com/StarcounterApps/Launchpad/tree/demo/multiple-icons

**Comment by Mihaiii** [comment]
Multiple icons can be added with current latest RC version (no change in Launchpad is required).
Closing.
